### ISSUE TITLE
Connect learners more from RWeka package to mlr3learners.rweka

### ISSUE THREAD

**Issue by henrifnk** [mlr-org/mlr3learners#114]
Add more Learners from `RWeka` to `mlr3learners.rweka`.
[mlr3learners.rweka](https://github.com/mlr3learners/mlr3learners.rweka)

[Pull Request](https://github.com/mlr3learners/mlr3learners.rweka/pull/4)...
Note: CI won't run until repo is transfered to a `mlr3learners` Oranisation, because drat doesn't work at private repos

**Comment by pat-s** [comment]
> Note: CI won't run until repo is transfered to a mlr3learners Oranisation, because drat doesn't work at private repos

CI != drat and the drat stuff is not causing this issue. It is because `TIC_DEPLOY_KEY` is not set and this causes issues in PRs.

**Comment by pat-s** [comment]
I think its because GHA secrets are not available in forked PRs and then {tic} complains that no deploy key could be found. 

You have write permissions to mlr3learners repos -> no reasons to use a fork. Please transfer the content into a branch of the respective package and remove your fork to clear things up :)

I'll resolve the forked PRs issues some other time.

**Comment by henrifnk** [comment]
All right I adapted your changes and added a branch to the repo

**Comment by pat-s** [comment]
Thanks. Please open a PR :) It would also be great if there could be a hyperlink in the first comment of this issue so I can more easily jump to the repo of the learner.
