### ISSUE TITLE
XGBoost learner uses wrong good/bad logic

### ISSUE THREAD

**Issue by randomuserflx** [mlr-org/mlr3learners#167]
The translation of factors when using a classifier with 0/1 is exactly the opposite of the logic used in the task. In my classification I might set good to "0" (which in many settings would be the default setting and is also the default value). However, when handed to xgb.predict(), the labels are exactly the opposite. This can lead to much confusion (plotted SHAP values will follow the opposite logic for example).

![image](https://user-images.githubusercontent.com/49711176/99705942-64245480-2a68-11eb-8917-3eb25d1f8534.png)

**Comment by mllg** [comment]
@be-marc can you have a look?

**Comment by be-marc** [comment]
@randomuserflx  What do you mean by "when handed to `xgb.predict()`, the labels are exactly the opposite"?

Both cases seem to work.

```r
# pos is 0 and neg is 1
task = tsk("pima")
data = task$data()

data[, diabetes := as.factor(as.numeric(diabetes) - 1)]

task = TaskClassif$new("pima", backend = data, target = "diabetes", positiv = "0")

learner = lrn("classif.xgboost")
learner$train(task)

pred = learner$predict(task)
pred$score()

# pos is 1 and neg is 0
task = tsk("pima")
data = task$data()
data[, diabetes := as.factor(2 - as.numeric(data$diabetes))]

task = TaskClassif$new("pima", backend = data, target = "diabetes", positiv = "1")

learner = lrn("classif.xgboost")
learner$train(task)

pred = learner$predict(task)
pred$score()
```

**Comment by be-marc** [comment]
Internally, `learner$train(task)` recodes the positive class to `1` and the negative class to `0` and trains the model. Next, `learner$predict()` calls `predict.xgb.Booster()` which returns the probabilities for the positive class, and we build a `Prediction` object. The classes are correctly assigned in the `Prediction` object, even if the positive class is encoded with "0" (Check `pred$confusion` for both examples). I do not see a mistake on our part. 

I do not understand when you encounter switched labels. Maybe if you leave the mlr3 framework? Let's assume your positive class is encoded with "0" in the `Task`. After using `learner$train()`, you extract the xgboost model and predict new data with `predict.xgb.Booster()`. In this case, you have to know that the returned probabilities refer to the positive class encoded with `0` in the data set. A function (to calculate SHAP values?) could falsely assume that the probabilities refer to the negative class encoded with `1`. In this case, you are out of luck and you should encode the positive class to `1` in your data. Note that `xgboost` assumes that your positive class is encoded with `1`. Otherwise, early stopping e.g. with a ppv measure does not work (https://github.com/mlr-org/mlr3learners/issues/32#issuecomment-534466863).

**Comment by mllg** [comment]
AFAICT, mlr3 is doing things correctly internally. 

`xgboost` has the convention that the positive class must be encoded as integer `1`, and mlr3 follows this conventions by converting the factor of binary class labels accordingly.

I agree that this may be confusing if you happen to use the string "0" as label for the positive class and the string "1" as label for the negative class. Unfortunately, I don't see how we can improve here. 
To not make it unnecessarily complicated, I would suggest encoding the classes with meaningful labels directly during task construction ("high"/"low", "survived"/"died", ...) rather than using the labels 0 and 1.
